appname: "AdminDashboard"
charset: "UTF-8"

warnings: 0
show_stacktrace: 0
startup_info: 1

plugins:
  Database:
    driver: SQLite
    database: database/persistance.db

email:
  imapHost: 'imap.fastmail.com'
  imapPort: 993
  username: ''
  password: ''


# logging
logger: "console"
log: "debug"