warnings: 0
show_stacktrace: 0
startup_info: 1

plugins:
  Database:
    driver: SQLite
    database: database/AdminDashboard.db

email:
  username: ''
  password: ''

# logging
log: "warning"
logger: "file"
engines:
  logger:
    file:
      file: "logs/production.log"
